server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem
    username: root
    password: 3773032
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity